### ISSUE TITLE
Task: Sketch out website design for computers, tablets, and phones

### ISSUE THREAD

**Issue by lumen-novum** [Allen-ISD-Computer-Science/REPO_TimeManagement_2024#13]

**Comment by lumen-novum** [comment]
Supports story #12

**Comment by calla-goeun-lee** [comment]
385945f basic sketch for computer, we didn't had much time to finish the layouts for mobile device(including phones, tablets) but we will come back to it next week. Won't be much changes though, compared to the computer version.
