### ISSUE TITLE
Task: Digital UI Design - Sub Page #1

### ISSUE THREAD

**Issue by calla-goeun-lee** [Allen-ISD-Computer-Science/REPO_TimeManagement_2024#25]
1. **Design basic UI for sub page** 
2. **Design Timer, how to efficiently visualize timing concepts for users**
3. **Design Tasks, basic layout for day to day activities** 
-> main goal, user-friendly + simple + modern

**Comment by calla-goeun-lee** [comment]
afb26d7

**Comment by lumen-novum** [comment]
I love your design Calla! I think it's user-friendly, simple, and modern. 10/10!!!
